src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ToDoList $ToDoList = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Priority = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $CompletionDate = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getToDoList(): ?ToDoList
    {
        return $this->ToDoList;
    }

    public function setToDoList(?ToDoList $ToDoList): static
    {
        $this->ToDoList = $ToDoList;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPriority(): ?string
    {
        return $this->Priority;
    }

    public function setPriority(?string $Priority): static
    {
        $this->Priority = $Priority;

        return $this;
    }

    public function getCompletionDate(): ?\DateTimeInterface
    {
        return $this->CompletionDate;
    }

    public function setCompletionDate(\DateTimeInterface $CompletionDate): static
    {
        $this->CompletionDate = $CompletionDate;

        return $this;
    }
}

templates/list/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ToDoList{% endblock %}

{% block body %}
    <main class="w-25 m-auto my-5">
        <h1>Edit ToDoList</h1>
        {{ form_start(form) }}
        <div class="form-floating">
            {{ form_widget(form.name) }}
            {{ form_label(form.name) }}
        </div>
        {{ form_row(form._token) }}
        <button class="btn btn-secondary w-100" type="submit">{{ button_label|default('Save') }}</button>
    </main>
{% endblock %}

templates/list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ListController!{% endblock %}

{% block body %}
    <div class="w-100 m-auto my-5">
        <h2><a href="{{ path('app_lists_new') }}">Add new list <i class="fa fa-plus"></i></a></h2>

        <div class="row my-5">
            {% for list in lists %}
            <div class="col-md-4">
                <h2>
                    <a href="{{ path('app_lists_show', {id: list.id}) }}">{{ list.name }}</a>
                    <a href="{{ path('app_lists_edit', {id: list.id}) }}">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a href="{{ path('app_lists_delete', {id: list.id}) }}">
                        <i class="fa fa-trash-o"></i>
                    </a>
                </h2>
                <br>
                {% set i = 0 %}
                {% for task in list.tasks %}
                    {% if i < 5 %}
                        {% set i = i + 1 %}
                        <h4>{{ task.name }}</h4>
                    {% endif %}
                {% endfor %}
            </div>
            {% if loop.index % 3 == 0 %}
        </div><div class="row">
            {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/list/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ToDoList{% endblock %}

{% block body %}
    <main class="w-25 m-auto my-5">
    <h1>Create new ToDoList</h1>
    {{ form_start(form) }}
    <div class="form-floating">
        {{ form_widget(form.name) }}
        {{ form_label(form.name) }}
    </div>
    <button class="btn btn-secondary w-100" type="submit">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
    </main>
{% endblock %}

templates/list/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ToDoList{% endblock %}

{% block body %}
    <div class="w-100 m-auto">
    <h1>{{ list.name }}</h1>
    <h3>Tasks</h3>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Priority</th>
                <th>Completion Date</th>
                <th>Delete</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
            {% for task in list.tasks %}
                <tr id="row{{ task.id }}">
                    <td>
                        {{ task.name }}
                    </td>
                    <td>
                        {{ task.description }}
                    </td>
                    <td>
                        {{ task.priority }}
                    </td>
                    <td>
                        {{ task.completiondate|date('Y-m-d') }}
                    </td>
                    <td>
                        <label>
                            <input type="checkbox" class="delete-checkbox" data-task-id="{{ task.id }}">
                        </label>
                    </td>
                    <td>
                        <a href="{{ path('app_task_edit', {id: task.id, listId: list.id}) }}">
                            <i class="fa fa-edit"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <p class="text-start fs-2"><a href="{{ path('app_task_new', {listId: list.id}) }}">Add more task!</a></p>
    </div>
{% endblock %}